// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzaqjLBgaS9zAkpdz3CqUzVGRONxcanJQ',
    appId: '1:1024839263211:web:0f5578d296851e9c636fae',
    messagingSenderId: '1024839263211',
    projectId: 'gearshareapp-efbf4',
    authDomain: 'gearshareapp-efbf4.firebaseapp.com',
    storageBucket: 'gearshareapp-efbf4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxa9JqiAcsxOmWh0u5YutttseBGnKfk8k',
    appId: '1:1024839263211:android:da09fb2269ffb131636fae',
    messagingSenderId: '1024839263211',
    projectId: 'gearshareapp-efbf4',
    storageBucket: 'gearshareapp-efbf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-rWIZt8aTgxJKtyouVR8yMMmK4cVgUA0',
    appId: '1:1024839263211:ios:9d6813aa227c0002636fae',
    messagingSenderId: '1024839263211',
    projectId: 'gearshareapp-efbf4',
    storageBucket: 'gearshareapp-efbf4.firebasestorage.app',
    androidClientId: '1024839263211-dq8ej4uqo6tmrfe3die5v3ek434o07l6.apps.googleusercontent.com',
    iosClientId: '1024839263211-pvgejpi3mf4hbqbth5akdn8m9t0katd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gearShareProject',
  );

}